---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/dev}

inputs:
- name: concourse
- name: concourse-release-repo

run:
  path: concourse/ci/tasks/scripts/check-bosh-props
